### ISSUE TITLE
Pip install gives `ModuleNotFoundError`

### ISSUE THREAD

**Issue by magnusuMET** [metno/py-mmd-tools#227]
I tried making a new virtual environment with `python3.11.0` and then installed these tools using `pip install git+https://github.com/metno/py-mmd-tools.git`. When running `check_nc` I get
```
Traceback (most recent call last):
  File "/lustre/storeB/users/magnusu/pymmdtools/bin/check_nc", line 5, in <module>
    from script.check_nc import _main
ModuleNotFoundError: No module named 'script'
```

Maybe `script` should be added to https://github.com/metno/py-mmd-tools/blob/9ace2f22be9a03e8e1977f6c534e77502acf9b4b/setup.cfg#L32 or moved a directory down to the installed package?

**Comment by TAlonglong** [comment]
As a workaround I think you can prepend your command with `PYTHONPATH=.`

**Comment by TAlonglong** [comment]
I think is due to the use of entry_point here https://github.com/metno/py-mmd-tools/blob/master/setup.cfg#L48-L52

I'm not sure it this is the right use of entry point, but if we replace `script` with `py_mmd_tools` and move those scripts from `scripts` to `py_mmd_tools` I thkn we get what you expects.

We can discuss the exact solution
